<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Chronos.Core.Engine</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <WarningsAsErrors>nullable,CS1591</WarningsAsErrors>
        <WarningsNotAsErrors>NU1903</WarningsNotAsErrors>
        <NoWarn>$(NoWarn);NU1900;NU1903</NoWarn>
        <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
        <AssemblyName>Chronos.Core.Engine</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MessagePack" Version="3.1.7" />
        <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
        <PackageReference Include="NCrontab" Version="3.4.0" />
        <PackageReference Include="Serilog" Version="4.3.1" />
        <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
        <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Chronos.Core.Shared\Chronos.Core.Shared.csproj" />
        <ProjectReference Include="..\Chronos.Core.Sdk\Chronos.Core.Sdk.csproj" />
        <ProjectReference Include="..\Chronos.Core.Kernel\Chronos.Core.Kernel.csproj" />
    </ItemGroup>

</Project>
