<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <AnalysisLevel>latest-all</AnalysisLevel>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

        <!-- Read version from VERSION.txt -->
        <Version Condition="Exists('$(MSBuildThisFileDirectory)VERSION.txt')">$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)VERSION.txt').Trim())</Version>

        <Authors>BleedingOnTheEdge</Authors>
        <Company>BleedingOnTheEdge</Company>
        <Copyright>© 2026 BleedingOnTheEdge</Copyright>
        <Product>Razor</Product>
        <PackageProjectUrl>https://razor.BleedingOnTheEdge.com</PackageProjectUrl>
        <RepositoryUrl>https://github.com/BleedingOnTheEdge/razor</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>
</Project>