<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Chronos.Core.Kernel</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <WarningsAsErrors>nullable,CS1591</WarningsAsErrors>
        <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Chronos.Core.Abstractions\Chronos.Core.Abstractions.csproj" Condition="'$(UseLocalAbstractions)' == 'true'" />
        <PackageReference Include="Chronos.Core.Abstractions" Version="0.1.5" Condition="'$(UseLocalAbstractions)' != 'true'" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Chronos.Core.Kernel.UnitTests" />
        <InternalsVisibleTo Include="Chronos.Core.Kernel.IntegrationTests" />
    </ItemGroup>

</Project>
