<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Chronos.Core.Kernel</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <WarningsAsErrors>nullable,CS1591</WarningsAsErrors>
        <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Chronos.Core.Abstractions" Version="1.0.6" />
    </ItemGroup>

</Project>
