<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Chronos.Core.Shared</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Chronos.Core.Kernel" />
        <InternalsVisibleTo Include="Chronos.Core.Engine" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Chronos.Core.Sdk\Chronos.Core.Sdk.csproj" />
    </ItemGroup>

</Project>