<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Chronos.Kernel</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <WarningsAsErrors>nullable,CS1591</WarningsAsErrors>
        <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Chronos.Abstractions\Chronos.Abstractions.csproj" />
    </ItemGroup>

</Project>