<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <WarningsAsErrors>nullable,CS1591</WarningsAsErrors>
        <RootNamespace>Chronos.Samples</RootNamespace>

    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Chronos.Abstractions\Chronos.Abstractions.csproj"/>
        <ProjectReference Include="..\Chronos.Kernel\Chronos.Kernel.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Plugins\Strategies\CryptoSimpleRsi\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Chaos.NaCl.Standard" Version="1.0.0" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0"/>
    </ItemGroup>

</Project>