namespace Chronos.Core.Abstractions.Pluggability;

/// <summary>A single execution slice generated by an algorithm.</summary>
public sealed record ExecutionSlice
{
    /// <summary>Time to execute.</summary>
    public required DateTime ScheduledTime { get; init; }

    /// <summary>Volume to execute.</summary>
    public required double Volume { get; init; }

    /// <summary>
    /// Optional Limit price for this slice. <c>null</c> means market order.
    /// Must be explicitly set (including to null) to confirm intentional omission.
    /// </summary>
    public required double? LimitPrice { get; init; }
}
