using Chronos.Core.Abstractions.Shared;
using Chronos.Core.Abstractions.Strategies;
using Chronos.Core.Abstractions.Adapters;

namespace Chronos.Core.Abstractions.Pluggability;

/// <summary>Portfolio-level risk gate called before every order submission.</summary>
public interface IRiskManager
{
    /// <summary>Evaluates if an order should be placed.</summary>
    bool AllowOrder(RiskContext context, out string? rejectReason);
    /// <summary>Evaluates ongoing portfolio risk.</summary>
    RiskSignal Evaluate(RiskContext context);
}

/// <summary>Context record for Risk Manager evaluation.</summary>
public sealed record RiskContext
{
    /// <summary>Current account balance.</summary>
    public required double Balance { get; init; }
    /// <summary>Current equity.</summary>
    public required double Equity { get; init; }
    /// <summary>Max drawdown recorded.</summary>
    public required double MaxDrawdown { get; init; }
    /// <summary>Max daily drawdown recorded.</summary>
    public required double MaxDailyDrawdown { get; init; }
    /// <summary>Margin used.</summary>
    public required double MarginUsed { get; init; }
    /// <summary>Free margin.</summary>
    public required double FreeMargin { get; init; }
    /// <summary>List of open positions.</summary>
    public required IReadOnlyList<Position> OpenPositions { get; init; }
    /// <summary>Order requested.</summary>
    public required AdapterOrderRequest? PendingOrder { get; init; }
    /// <summary>Symbol metadata.</summary>
    public required SymbolProperties? SymbolProperties { get; init; }
}

/// <summary>Risk management signals.</summary>
public enum RiskSignal
{
    /// <summary>Allow operations</summary>
    Allow,
    /// <summary>Warning thresholds</summary>
    Warn,
    /// <summary>Halt all activity</summary>
    Halt
}

/// <summary>Calculates the volume to trade based on account state and risk parameters.</summary>
public interface IPositionSizer
{
    /// <summary>Calculates position sizing volume.</summary>
    double CalculateVolume(PositionSizingContext context);
}

/// <summary>Context record for Position Sizer.</summary>
public sealed record PositionSizingContext
{
    /// <summary>Account equity.</summary>
    public required double AccountEquity { get; init; }
    /// <summary>Risk percentage to apply.</summary>
    public required double RiskPercent { get; init; }
    /// <summary>Stop loss distance.</summary>
    public required double StopLossDistance { get; init; }
    /// <summary>Symbol metadata.</summary>
    public required SymbolProperties SymbolProperties { get; init; }
    /// <summary>Entry price.</summary>
    public required double EntryPrice { get; init; }
    /// <summary>Account leverage.</summary>
    public required double Leverage { get; init; }
}

/// <summary>Classifies the current market into a discrete regime.</summary>
public interface IMarketRegimeDetector
{
    /// <summary>Detects the current market regime.</summary>
    MarketRegime Detect(string symbol, TickWindow tickWindow);
}

/// <summary>Market regimes.</summary>
public enum MarketRegime
{
    /// <summary>Unknown regime.</summary>
    Unknown,
    /// <summary>Trending regime.</summary>
    Trending,
    /// <summary>Range bound regime.</summary>
    RangeBound,
    /// <summary>High Volatility regime.</summary>
    HighVolatility,
    /// <summary>Low Volatility regime.</summary>
    LowVolatility,
    /// <summary>Breakout regime.</summary>
    Breakout
}

/// <summary>Smart order execution algorithm (TWAP, VWAP, Iceberg, etc.).</summary>
public interface IExecutionAlgorithm
{
    /// <summary>Generates a sequence of slices.</summary>
    IAsyncEnumerable<ExecutionSlice> GenerateSlicesAsync(ExecutionAlgorithmRequest request, CancellationToken cancellationToken);
}

/// <summary>Execution Algorithm Request.</summary>
public sealed record ExecutionAlgorithmRequest
{
    /// <summary>Symbol.</summary>
    public required string Symbol { get; init; }
    /// <summary>Trade direction.</summary>
    public required OrderType Direction { get; init; }
    /// <summary>Total volume.</summary>
    public required double TotalVolume { get; init; }
    /// <summary>Start time.</summary>
    public required DateTime StartTime { get; init; }
    /// <summary>End time.</summary>
    public required DateTime EndTime { get; init; }
    /// <summary>Symbol properties.</summary>
    public required SymbolProperties SymbolProperties { get; init; }
}

/// <summary>A single execution slice generated by an algorithm.</summary>
public sealed record ExecutionSlice
{
    /// <summary>Time to execute.</summary>
    public required DateTime ScheduledTime { get; init; }
    /// <summary>Volume to execute.</summary>
    public required double Volume { get; init; }
    /// <summary>Optional Limit price.</summary>
    public required double? LimitPrice { get; init; }
}

/// <summary>Provides historical and live data independently of execution.</summary>
public interface IMarketDataProvider
{
    /// <summary>Name of the provider.</summary>
    string ProviderName { get; }
    /// <summary>Fetches history data to binary.</summary>
    Task<HistoricalDataResponse> FetchHistoryToBinaryFileAsync(HistoricalDataRequest request, CancellationToken cancellationToken);
    /// <summary>Deletes the requested history file.</summary>
    Task DeleteHistoryFileAsync(string filePath);
    /// <summary>Notifies engine safe to delete.</summary>
    Task NotifyFileSafeToDeleteAsync(string filePath);
    /// <summary>Subscribes to symbol ticks.</summary>
    Task SubscribeAsync(string symbol);
    /// <summary>Unsubscribes from symbol ticks.</summary>
    Task UnsubscribeAsync(string symbol);
    /// <summary>Tick received event.</summary>
    event Action<string, Tick> OnTickReceived;
}

/// <summary>Backtest engine abstraction.</summary>
public interface IBacktestEngine
{
    /// <summary>Engine name.</summary>
    string EngineName { get; }
}

/// <summary>Generates a formatted report.</summary>
public interface IReportGenerator
{
    /// <summary>Format (e.g. HTML, PDF).</summary>
    string Format { get; }
    /// <summary>Generates the report asynchronously.</summary>
    Task<byte[]> GenerateAsync(object request, CancellationToken cancellationToken);
}

/// <summary>Calculates custom performance metrics.</summary>
public interface IMetricsProvider
{
    /// <summary>Calculates a dictionary of custom metrics.</summary>
    IReadOnlyDictionary<string, double> Calculate(object result, double initialBalance);
}

/// <summary>Engine capability manifest.</summary>
public sealed record EngineCapabilityManifest
{
    /// <summary>Engine version.</summary>
    public required string EngineVersion { get; init; }
    /// <summary>Kernel version.</summary>
    public required string KernelVersion { get; init; }
    /// <summary>Abstractions version.</summary>
    public required string AbstractionsVersion { get; init; }
    /// <summary>Runtime version.</summary>
    public required string RuntimeVersion { get; init; }
    /// <summary>Operating System.</summary>
    public required string OS { get; init; }
    /// <summary>Available capabilities.</summary>
    public required IReadOnlyList<CapabilityDescriptor> Capabilities { get; init; }
    /// <summary>Currently loaded plugins.</summary>
    public required IReadOnlyList<LoadedPlugin> LoadedPlugins { get; init; }
    /// <summary>Boot timestamp.</summary>
    public required DateTime BootTime { get; init; }
}

/// <summary>A specific engine capability.</summary>
public sealed record CapabilityDescriptor
{
    /// <summary>Name of capability.</summary>
    public required string Name { get; init; }
    /// <summary>Version of capability.</summary>
    public required string Version { get; init; }
    /// <summary>Enabled state.</summary>
    public required bool IsEnabled { get; init; }
    /// <summary>Flags configuration.</summary>
    public IReadOnlyList<string> Flags { get; init; } = [];
}

/// <summary>A loaded plugin state.</summary>
public sealed record LoadedPlugin
{
    /// <summary>Plugin Id.</summary>
    public required string PluginId { get; init; }
    /// <summary>Plugin Version.</summary>
    public required string Version { get; init; }
    /// <summary>Type of the plugin.</summary>
    public required string PluginType { get; init; }
    /// <summary>SDK target version.</summary>
    public required string SdkVersion { get; init; }
    /// <summary>Is plugin valid.</summary>
    public required bool IsValid { get; init; }
    /// <summary>Validation error reason if invalid.</summary>
    public string? ValidationError { get; init; }
}

/// <summary>Marks an interface or class with a specific capability version requirement.</summary>
[AttributeUsage(AttributeTargets.Interface | AttributeTargets.Class, AllowMultiple = true)]
public sealed class ChronosFeatureAttribute : Attribute
{
    /// <summary>Name of the feature.</summary>
    public string FeatureName { get; }
    /// <summary>Minimum version required.</summary>
    public string MinVersion { get; }

    /// <summary>Initializes a new instance.</summary>
    public ChronosFeatureAttribute(string featureName, string minVersion = "1.0.0")
    {
        FeatureName = featureName;
        MinVersion = minVersion;
    }
}
